// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNZ9K_1dO2zhxrWeOYFHILwcphAd9hcDE',
    appId: '1:913562624381:web:e40d6adceb43b8d5332c14',
    messagingSenderId: '913562624381',
    projectId: 'gcp-banorte-hackaton-team-18',
    authDomain: 'gcp-banorte-hackaton-team-18.firebaseapp.com',
    storageBucket: 'gcp-banorte-hackaton-team-18.appspot.com',
    measurementId: 'G-HZQZ3EMTV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXFl7r4Zo2dWBFZowbBO7ZFQPE9OzytpA',
    appId: '1:913562624381:android:f5bc5e38ede7b80a332c14',
    messagingSenderId: '913562624381',
    projectId: 'gcp-banorte-hackaton-team-18',
    storageBucket: 'gcp-banorte-hackaton-team-18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr0YZQaDyTkq5_lo55ItvVXaHu1lizQdY',
    appId: '1:913562624381:ios:005d72248b40fc19332c14',
    messagingSenderId: '913562624381',
    projectId: 'gcp-banorte-hackaton-team-18',
    storageBucket: 'gcp-banorte-hackaton-team-18.appspot.com',
    iosBundleId: 'com.example.hackBanorteReto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr0YZQaDyTkq5_lo55ItvVXaHu1lizQdY',
    appId: '1:913562624381:ios:005d72248b40fc19332c14',
    messagingSenderId: '913562624381',
    projectId: 'gcp-banorte-hackaton-team-18',
    storageBucket: 'gcp-banorte-hackaton-team-18.appspot.com',
    iosBundleId: 'com.example.hackBanorteReto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNZ9K_1dO2zhxrWeOYFHILwcphAd9hcDE',
    appId: '1:913562624381:web:3c5b4cf9b500fa1b332c14',
    messagingSenderId: '913562624381',
    projectId: 'gcp-banorte-hackaton-team-18',
    authDomain: 'gcp-banorte-hackaton-team-18.firebaseapp.com',
    storageBucket: 'gcp-banorte-hackaton-team-18.appspot.com',
    measurementId: 'G-QRD4Q5GHEJ',
  );
}
